# Generated by Django 3.1.5 on 2021-01-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaplatform', '0002_auto_20210118_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
